#!/bin/sh

if clang-format --version &>/dev/null ; then
    if ! git diff --quiet ; then
        # echo "No staged changes, skipping clang-format"
        exit 0
    fi
    GIT_HOME=$(git rev-parse --show-toplevel)
    chmod +x "$GIT_HOME/clang-format.sh"
    "$GIT_HOME/clang-format.sh"
    git add "$GIT_HOME"
    # git add .
else
    echo "clang-format not installed, please use your distro's package manager or on windows run: winget install --id=LLVM.ClangFormat -e"
fi

exit 0