#!/bin/sh
# Tells the os where to find the executable to run the file with, for this its "sh" which is a shell
# But it could even be something like /usr/bin/python for a python program

# Checks if clang-format is installed and gets rid of its output (what it prints out) using &>/dev/null
if clang-format --version &>/dev/null ; then
    # Checks to make sure there actually are changes before running the script
    if git diff --cached --quiet ; then
        # echo "No staged changes, skipping clang-format"
        exit 0
    fi
    # Sets GIT_HOME to the absolute path of the top level of the git repo
    GIT_HOME=$(git rev-parse --show-toplevel)
    # Makes the clang-format script executable
    chmod +x "$GIT_HOME/clang-format.sh"
    # Executes the clang-format script
    "$GIT_HOME/clang-format.sh"
    # Git adds all the files
    git add "$GIT_HOME"
    # git add .
else
    # Tells to user to install clang-format and how to do so
    echo "clang-format not installed, please use your distro's package manager or on windows run: winget install --id=LLVM.ClangFormat -e"
fi

# Exits the script
exit 0